# Generated by Django 6.0 on 2025-12-05 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='createsd_at',
            new_name='created_at',
        ),
    ]
